n1 = int(input("primeiro valor: "))
n2 = int(input("Segundo valor: "))
s = (n1 + n2)
m = (n1 * n2)
d = (n1 / n2)
di = (n1 // n2)
e = (n1 **n2)
print(f"A soma e {s}\nO Produto e {m}\nA Divisao e {d:.2f}\nDivisao inteira {di}\nE Potencia {e}")