n1 = int(input("primeiro valor: "))
n2 = int(input("Segundo valor: "))
s = (n1 + n2)
m = (n1 * n2)
d = (n1 / n2)
di = (n1 // n2)
e = (n1 **n2)
print(f"A soma e {s} \n O Produto e {m} \n A Divisao e {d:.2f} \n Divisao inteira {di} \n E Potencia {e}")