from time import sleep
print("=" * 10)
print("BEM VINDO")
print("=" * 10)
n1 = int(input("primeiro valor: "))
n2 = int(input("Segundo valor: "))
print("=" * 15)
print("CARREGANDO...")
print("=" * 15)
sleep(2)
s = (n1 + n2)
m = (n1 * n2)
d = (n1 / n2)
di = (n1 // n2)
e = (n1 **n2)
print("=" * 15)
print(f"A soma e {s}\nO Produto e {m}\nA Divisao e {d:.2f}\nDivisao inteira {di}\nE Potencia {e}")
print("=" * 15)