n1 = int(input('digite um valor: '))
n2 = int(input('digite outro valor: '))
s = (n1 + n2)
m = (n1 * n2)
d = (n1 / n2)
di = (n1 // n2)
e = (n1 ** n2)
print(f'A soma e {s} o produto e {m} e a divisao e {d:.2f}')
print(f'Divisao inteira {di} e potencia {e}')