salario = float(input("Qual e o Salario do Funcionario? R$"))
novo = salario + (salario * 15/100)
print(f"Um funcionario que ganhava R${salario}", end="")
print("Com 15% de aumento")
print(f"Passa A Receber R${novo}")